/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elfikysys.GUI;

import Models.DatabaseConnection;
import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javcoder
 */
public class dataContract extends javax.swing.JFrame {

    private String name;
    private String phone;
    private String address;
    private String dateContract;
    private String requir;
    private String notes;
    private int code;
    private int elmadfoaa;
    private int tips;
    private int totalprice;
    private int paydays;
    private int paymonths;
    private int recievedays;
    private int recievemonths;
    //code, name, address, phone, requirements, 
    //notes , totalprice , emdfoaa , tips , payday , paymonth , recieveday , recievemonth , dateContract

    public dataContract(int cod, String nam, String addres, String phon, String requirmets, String note,
             int total, int emdf, int tipss, int payday, int paymonth, int reciday, int recimonth, String contr) {
        this.code = cod;
        this.name = nam;
        this.address = addres;
        this.phone = phon;
        this.requir = requirmets;
        this.notes = note;
        this.totalprice = total;
        this.elmadfoaa = emdf;
        this.tips = tipss;
        this.paydays = payday;
        this.paymonths = paymonth;
        this.recievedays = reciday;
        this.recievemonths = recimonth;
        this.dateContract = contr;
        initComponents();
        this.setLocationRelativeTo(null);

        putData(code, name, address, phone, requir, notes, totalprice, elmadfoaa, tips, paydays, paymonths, recievedays, recievemonths, dateContract);
        NoteTextArea.setLineWrap(true);
        NoteTextArea.setWrapStyleWord(true);
        NoteTextArea.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        descriptionTable.setRowHeight(30);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        descriptionTable.setDefaultRenderer(String.class, centerRenderer);
        for (int i = 0; i < descriptionTable.getColumnCount(); i++) {
            descriptionTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NameClientField = new javax.swing.JTextField();
        codeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalPriceField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipsField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        elmadfoaaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        addressField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateContractField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        recievedateField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        recievedatemField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        paydateField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        paydatemField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        showBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NoteTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTable = new javax.swing.JTable();
        showBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("صفحه عرض تفاصيل العقد");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("عرض تفاصيل العقد ");

        addBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addBtn.setText("اضافه");
        addBtn.setEnabled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        EditBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EditBtn.setText("تعديل");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteBtn.setText("حذف");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("اسم العميل :");

        NameClientField.setEditable(false);
        NameClientField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        NameClientField.setForeground(new java.awt.Color(0, 0, 204));
        NameClientField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NameClientField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        codeField.setEditable(false);
        codeField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        codeField.setForeground(new java.awt.Color(0, 0, 204));
        codeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("الكود :");

        phoneField.setEditable(false);
        phoneField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phoneField.setForeground(new java.awt.Color(0, 0, 204));
        phoneField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        phoneField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("الفون:");

        totalPriceField.setEditable(false);
        totalPriceField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        totalPriceField.setForeground(new java.awt.Color(0, 0, 204));
        totalPriceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPriceField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        totalPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalPriceFieldKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("الاجمالي :");

        tipsField.setEditable(false);
        tipsField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tipsField.setForeground(new java.awt.Color(0, 0, 204));
        tipsField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tipsField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tipsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipsFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("الباقي:");

        elmadfoaaField.setEditable(false);
        elmadfoaaField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        elmadfoaaField.setForeground(new java.awt.Color(0, 0, 204));
        elmadfoaaField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        elmadfoaaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        elmadfoaaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elmadfoaaFieldKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("المدفوع:");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/go_next_blue_60x40.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addressField1.setEditable(false);
        addressField1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        addressField1.setForeground(new java.awt.Color(0, 0, 204));
        addressField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        addressField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("العنوان :");

        jLabel11.setText("المواصفات:");

        jLabel12.setText("الملاحظات");

        dateContractField.setEditable(false);
        dateContractField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        dateContractField.setForeground(new java.awt.Color(51, 0, 204));
        dateContractField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateContractField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateContractFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("تاريخ العقد");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("تاريخ الاستلام");

        recievedateField1.setEditable(false);
        recievedateField1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        recievedateField1.setForeground(new java.awt.Color(0, 0, 204));
        recievedateField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        recievedateField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        recievedateField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recievedateField1KeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("يوم");

        recievedatemField2.setEditable(false);
        recievedatemField2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        recievedatemField2.setForeground(new java.awt.Color(0, 0, 204));
        recievedatemField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        recievedatemField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        recievedatemField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recievedatemField2KeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("شهر");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recievedatemField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(recievedateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(recievedateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recievedatemField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("تاريخ الدفع");

        paydateField.setEditable(false);
        paydateField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        paydateField.setForeground(new java.awt.Color(0, 0, 204));
        paydateField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paydateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        paydateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paydateFieldKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("يوم");

        paydatemField.setEditable(false);
        paydatemField.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        paydatemField.setForeground(new java.awt.Color(0, 0, 204));
        paydatemField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paydatemField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        paydatemField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paydatemFieldKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("شهر");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paydatemField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(paydateField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(paydateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paydatemField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        showBtn.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        showBtn.setText("عرض الفواتير");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        NoteTextArea.setColumns(20);
        NoteTextArea.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NoteTextArea.setForeground(new java.awt.Color(0, 0, 204));
        NoteTextArea.setRows(5);
        jScrollPane1.setViewportView(NoteTextArea);

        descriptionTable.setBackground(new java.awt.Color(255, 255, 153));
        descriptionTable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        descriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "اجمالي السعر", "الكميه", "الاسم"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(descriptionTable);

        showBtn1.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        showBtn1.setText("عرض الفاتوره الحاليه");
        showBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(backBtn)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(elmadfoaaField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateContractField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(263, 263, 263)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(92, 92, 92)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(showBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NameClientField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipsField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameClientField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elmadfoaaField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(dateContractField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipsField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ClientsList list = new ClientsList();
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        NameClientField.setEditable(true);
        phoneField.setEditable(true);
        totalPriceField.setEditable(true);
        tipsField.setEditable(true);
        elmadfoaaField.setEditable(true);
        addressField1.setEditable(true);
        NoteTextArea.setEditable(true);
        paydateField.setEditable(true);
        paydatemField.setEditable(true);
        recievedateField1.setEditable(true);
        recievedatemField2.setEditable(true);
        addBtn.setEnabled(true);
    }//GEN-LAST:event_EditBtnActionPerformed
    String require;
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String itemName = NameClientField.getText();
        int itemCode = Integer.parseInt(codeField.getText());
        String phone = phoneField.getText();
        String address = addressField1.getText();
        String datecontract = dateContractField.getText();
        String require = this.require;
        String note = NoteTextArea.getText();
        int payday = Integer.parseInt(paydateField.getText());
        int paymonth = Integer.parseInt(paydatemField.getText());
        int recievepay = Integer.parseInt(recievedateField1.getText());
        int recievemonth = Integer.parseInt(recievedatemField2.getText());
        int totalPric = Integer.parseInt(totalPriceField.getText());
        int tip = Integer.parseInt(tipsField.getText());
        int elmadfoa = Integer.parseInt(elmadfoaaField.getText());

        if (itemName.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }

        if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;

        }
        if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (require.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (note.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (totalPriceField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }

        if (tipsField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }

        if (elmadfoaaField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (paydateField.getText().equals("") || payday > 31 || payday < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }
        if (paydatemField.getText().equals("") || paymonth > 12 || paymonth < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }
        if (recievedatemField2.getText().equals("") || recievemonth > 12 || recievemonth < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }
        if (recievedateField1.getText().equals("") || recievepay > 31 || recievepay < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }

        updateData(itemCode, itemName, address, phone, require, note, totalPric, elmadfoa, tip, payday, paymonth, recievepay, recievemonth, datecontract);
         ImportClient mmm=new ImportClient();
        mmm.setVisible(true);
        mmm.dispose();
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String itemName = NameClientField.getText();
        int itemCode = Integer.parseInt(codeField.getText());
        String phone = phoneField.getText();
        String address = addressField1.getText();
        String datecontract = dateContractField.getText();
        String require = this.require;
        String note = NoteTextArea.getText();
        int payday = Integer.parseInt(paydateField.getText());
        int paymonth = Integer.parseInt(paydatemField.getText());
        int recievepay = Integer.parseInt(recievedateField1.getText());
        int recievemonth = Integer.parseInt(recievedatemField2.getText());
        int totalPric = Integer.parseInt(totalPriceField.getText());
        int tip = Integer.parseInt(tipsField.getText());
        int elmadfoa = Integer.parseInt(elmadfoaaField.getText());

        if (itemName.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }

        if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;

        }
        if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (require.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (note.equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (totalPriceField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }

        if (tipsField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }

        if (elmadfoaaField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ");
            return;
        }
        if (paydateField.getText().equals("") || payday > 31 || payday < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }
        if (paydatemField.getText().equals("") || paymonth > 12 || paymonth < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }
        if (recievedatemField2.getText().equals("") || recievemonth > 12 || recievemonth < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }
        if (recievedateField1.getText().equals("") || recievepay > 31 || recievepay < 0) {
            JOptionPane.showMessageDialog(null, "الرجاء من فضلك لا تترك اي خانه فارغه ويجب عليك ادخال رقم صحيح ");
            return;
        }

        deleteRecord(itemCode);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void dateContractFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateContractFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateContractFieldActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:
        int co = Integer.parseInt(codeField.getText());
        ShowContracts show = new ShowContracts(co);
        show.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_showBtnActionPerformed

    private void showBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtn1ActionPerformed
        // TODO add your handling code here:
        show m=new show(Long.parseLong(codeField.getText()),1);
    }//GEN-LAST:event_showBtn1ActionPerformed

    private void elmadfoaaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elmadfoaaFieldKeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_elmadfoaaFieldKeyTyped

    private void totalPriceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalPriceFieldKeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceFieldKeyTyped


    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldKeyTyped

    private void tipsFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipsFieldKeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tipsFieldKeyTyped

    private void recievedateField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recievedateField1KeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_recievedateField1KeyTyped

    private void recievedatemField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recievedatemField2KeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_recievedatemField2KeyTyped

    private void paydateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paydateFieldKeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_paydateFieldKeyTyped

    private void paydatemFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paydatemFieldKeyTyped
  char c = evt.getKeyChar();
        if (c < 48 || c > 57) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_paydatemFieldKeyTyped

    private void putData(int code, String name, String address, String phone, String requir, String notes, int totalprice, int elmadfoaa, int tips, int paydays, int paymonths, int recievedays, int recievemonths, String dateContract) {
        NameClientField.setText(name);
        codeField.setText(String.valueOf(code));
        phoneField.setText(phone);
        totalPriceField.setText(String.valueOf(totalprice));
        tipsField.setText(String.valueOf(tips));
        elmadfoaaField.setText(String.valueOf(elmadfoaa));
        addressField1.setText(address);
        require = requir.substring(1, requir.length()-1);
        DefaultTableModel model = (DefaultTableModel) descriptionTable.getModel();
        String toc[]=require.split(",");
        for(int i=0;i<toc.length;i+=3)
        {
            model.addRow(new Object[]{toc[i],toc[i+1],toc[i+2]});
        }
        NoteTextArea.setText(notes);
        paydateField.setText(String.valueOf(paydays));
        paydatemField.setText(String.valueOf(paymonths));
        recievedateField1.setText(String.valueOf(recievedays));
        recievedatemField2.setText(String.valueOf(recievemonths));
        dateContractField.setText(dateContract);
    }

    private void updateData(int itemCode, String itemName, String address, String phone, String require, String note, int totalPric, int elmadfoa, int tip, int payday, int paymonth, int recievepay, int recievemonth, String datecontract) {
        Connection conn = null;
        PreparedStatement ps = null;
        int result = 0;
        String updateQuery = "UPDATE contracts SET Name=?,Address=?,Phone=?,Requirements=?,Notes=?,Totalprice=?,Elmadfoaa=?,Teps=?,DayDafaa=?,MonthDafaa=?,DayEstlam=?,MonthEstlam=?,dayConytact=? WHERE Code = '" + itemCode + "' ";

        try {
            conn = DatabaseConnection.getconnection();
            ps = conn.prepareStatement(updateQuery);
            ps.setString(1, itemName);
            ps.setString(2, address);
            ps.setString(3, phone);
            ps.setString(4, require);
            ps.setString(5, note);
            ps.setInt(6, totalPric);
            ps.setInt(7, elmadfoa);
            ps.setInt(8, tip);
            ps.setInt(9, payday);
            ps.setInt(10, paymonth);
            ps.setInt(11, recievepay);
            ps.setInt(12, recievemonth);
            ps.setString(13, datecontract);
            result = ps.executeUpdate();
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "تم عمليه تعديل العقد ");
            } else {
                JOptionPane.showMessageDialog(null, "هناك خطا في عمليه التعديل ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataContract.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }

                if (ps != null) {
                    ps.close();
                }
            } catch (Exception e) {
            }
        }
    }

    private void deleteRecord(int itemCode) {
        Connection conn = null;
        PreparedStatement ps = null;
        int result = 0;
        String deleteQuery = "DELETE FROM contracts WHERE  Code = '" + itemCode + "' ";

        try {
            conn = DatabaseConnection.getconnection();
            ps = conn.prepareStatement(deleteQuery);
            result = ps.executeUpdate();
            if (result != 0) {
                JOptionPane.showMessageDialog(null, "تم عمليه حذف العقد ");
            } else {
                JOptionPane.showMessageDialog(null, "هناك خطا في عمليه التعديل ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataContract.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }

                if (ps != null) {
                    ps.close();
                }
            } catch (Exception e) {
            }
        }

        ClientsList list = new ClientsList();
        list.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataContract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataContract(1, "dfdf", "dfd", "dfdfdf", "fffdfd", "sfdd", 11, 11, 33, 23, 23, 11, 11, "ddfd").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField NameClientField;
    private javax.swing.JTextArea NoteTextArea;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addressField1;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField codeField;
    private javax.swing.JTextField dateContractField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable descriptionTable;
    private javax.swing.JTextField elmadfoaaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField paydateField;
    private javax.swing.JTextField paydatemField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField recievedateField1;
    private javax.swing.JTextField recievedatemField2;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton showBtn1;
    private javax.swing.JTextField tipsField;
    private javax.swing.JTextField totalPriceField;
    // End of variables declaration//GEN-END:variables

}
